# Generated by Django 4.2.1 on 2023-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.CharField(default='', max_length=100),
        ),
    ]
