# Generated by Django 4.2.1 on 2023-05-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_username_field_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
