# Generated by Django 4.2 on 2023-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.CharField(default='0,', max_length=1024),
        ),
    ]
